# Generated by Django 4.1.7 on 2023-10-05 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_movie_alter_customuser_email_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='genres',
        ),
    ]
