# Generated by Django 4.1.7 on 2023-10-05 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_remove_collection_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='movies',
            field=models.ManyToManyField(related_name='c', to='playlist.movie'),
        ),
        migrations.RemoveField(
            model_name='collection',
            name='owner',
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='collection',
            name='owner',
            field=models.ManyToManyField(related_name='customuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
