# Generated by Django 4.1.7 on 2023-10-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0008_alter_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
