# Generated by Django 4.1.7 on 2023-10-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0011_requestcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='requestcount',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
